[project]
name = "pyalloq"
version = "0.1.0"
description = "A modern Python SDK for quant portfolio optimization. (Work in Progress)"
readme = "README.md"
authors = [
    { name = "Siddeshkanth", email = "siddeshkanth.logonathan@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"
